### ISSUE TITLE
Fixed Pitch vs Non-fixed pitch

### ISSUE THREAD

**Issue by djtuBIG-MaliceX** [leecher1337/esfmbank#1]
Hello, just thought I'd leave a line here to say I've had some success with using this on my Ryzen 3900X setup with an ASM1083 PCIe-PCI bridge adapter.  I've got two ES1938S PCI cards both have worked great with this along with the Win11 64-bit driver from the [other repo](https://github.com/leecher1337/es1969).

I've spent some time fiddling with the ESFM Bank Editor making my own patches and reporting two things.

### 1. Fixed pitch flag doesn't "write"
While one can audition existing patches with Fixed pitch set, one cannot toggle on/off for own patches.  Suspect it's a bug or a missing opcode to send to the hardware when toggling the "Fixed Pitch" flag.

### 2. When Fixed pitch flag is disabled (default melodic mode), F-num+Block register has a different layout.

I've actually spent some time reverse-engineering this behaviour and have determined the following:
![image](https://github.com/leecher1337/esfmbank/assets/3403183/59366861-2ed6-4a95-8e0b-f4d57c743a73)

On closer inspection and auditioning, the Block register is also shared, which based on the numbers and bits set, I've determined this to have the following layout:

```
=================================================================
| X | X | X | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 
=================================================================
|XXXXXXXXXXX|--BlockNum-|-----------------F-Num-----------------|  = Fixed pitch enabled
=================================================================
|XXXXXXXXXXX|   Coarse Tune     |   Fine Tune (signed)  |CT bits|  = Fixed pitch disabled (default)
|XXXXXXXXXXX| bits 6..2 (signed)|       bits 5..0       |  1..0 |
================================================================|

Sign bits:
- Fine tune: 5 (used within F-Num)
- Coarse Tune: 6 (used by Block Number)
```

Because of this, might need to look at having a UI pane toggle with fixed pitch on/off to re-use those register values and correspond to Coarse Tune/Fine Tune controls. :)

PS: Can also confirm tuning is flat from A440 correlating with [this other report](https://github.com/leecher1337/es1969/issues/4).

**Comment by djtuBIG-MaliceX** [comment]
Just to clarify, this is purely for input to the ESFM **driver interface**, not to the ESFM chip registers itself.  Seems the fact there's multiple places where F-num is being calculated one can conflate the two.

**Comment by leecher1337** [comment]
Thank you for your report!
Regarding the fixed pitch error, I can clearly hear a difference on "Play" when toggling the flag, so I was unable to reproduce that problem.
Thanks for pointing out the playback differences on fixed pitch, I should have picked them up from NATV.C, I hope current release now handles it correctly.

**Comment by djtuBIG-MaliceX** [comment]
Hello, thanks for solving that one.   Can confirm it all works!
Regarding the tick, yeah I can definitely hear it when pressing the GUI buttons to audition to have the changes take effect.  It's when auditioning using a MIDI keyboard is where it doesn't and I suppose requires the GUI action to 'send' the patch settings before auditioning the note.  Other than that, all works!

Thanks very much!
